name: CI

on: 
  push:
    branches: 
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.*'
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm ci
      
      - name: Running unittests
        run: npm test       
